### ISSUE TITLE
Error with last release

### ISSUE THREAD

**Issue by CondormanFr** [empierre/MyDomoAtHome#107]
I downloaded the last docker image.
I create a new config.js file like this : 

`{
"app_name": "MyDomoAtHomeMyName",
"auth": null,
"domoticz": {
"ssl": false,
"host": "192.168.1.XXX",
"port": "XXX",
"path": "/",
"auth": null,
},
"port": "3002",
"passcode": ""
}`

and I get this error : 

```
/usr/share/mydomoathome/app/node_modules/nconf/lib/nconf/stores/file.js:160
stdout
21:55:33
    throw new Error(&quot;Error parsing your configuration file: [&quot; + this.file + ']: ' + ex.message);
stdout
21:55:33
    ^
stdout
21:55:33
stdout
21:55:33
Error: Error parsing your configuration file: [/etc/mydomoathome/config.json]: Unexpected token }
stdout
21:55:33
    at File.loadSync (/usr/share/mydomoathome/app/node_modules/nconf/lib/nconf/stores/file.js:160:11)
stdout
21:55:33
    at Provider.add (/usr/share/mydomoathome/app/node_modules/nconf/lib/nconf/provider.js:137:23)
stdout
21:55:33
    at Provider.use (/usr/share/mydomoathome/app/node_modules/nconf/lib/nconf/provider.js:110:10)
stdout
21:55:33
    at Object.&lt;anonymous&gt; (/usr/share/mydomoathome/app/mdah.js:77:11)
stdout
21:55:33
    at Module._compile (module.js:409:26)
stdout
21:55:33
    at Object.Module._extensions..js (module.js:416:10)
stdout
21:55:33
    at Module.load (module.js:343:32)
stdout
21:55:33
    at Function.Module._load (module.js:300:12)
stdout
21:55:33
    at Function.Module.runMain (module.js:441:10)
stdout
21:55:33
    at startup (node.js:139:18)
stdout
21:55:33
error: Forever detected script exited with code: 1
stdout
21:55:33
error: Script restart attempt #1
stdout
21:55:34
/usr/share/mydomoathome/app/node_modules/nconf/lib/nconf/stores/file.js:160
stdout
21:55:34
    throw new Error(&quot;Error parsing your configuration file: [&quot; + this.file + ']: ' + ex.message);
stdout
21:55:34

```

**Comment by empierre** [comment]
yes a coma too far, I corrected both readme, sorry...

 "auth": null }  <-- no coma before a closing }

**Comment by CondormanFr** [comment]
It's better ... but I get a new error after :  

```

info:  url=http://192.168.X.XXX:XXXX?type=devices&amp;filter=utility&amp;order=Name, User-Agent=request
stdout
06:29:46
undefined:1
stdout
06:29:46
&lt;!DOCTYPE html&gt;
stdout
06:29:46
^
stdout
06:29:46
stdout
06:29:46
SyntaxError: Unexpected token &lt;
stdout
06:29:46
    at Object.parse (native)
stdout
06:29:46
    at Request._callback (/usr/share/mydomoathome/app/mdah.js:2188:18)
stdout
06:29:46
    at Request.self.callback (/usr/share/mydomoathome/app/node_modules/request/request.js:200:22)
stdout
06:29:46
    at emitTwo (events.js:87:13)
stdout
06:29:46
    at Request.emit (events.js:172:7)
stdout
06:29:46
    at Request.&lt;anonymous&gt; (/usr/share/mydomoathome/app/node_modules/request/request.js:1067:10)
stdout
06:29:46
    at emitOne (events.js:82:20)
stdout
06:29:46
    at Request.emit (events.js:169:7)
stdout
06:29:46
    at IncomingMessage.&lt;anonymous&gt; (/usr/share/mydomoathome/app/node_modules/request/request.js:988:12)
stdout
06:29:46
    at emitNone (events.js:72:20)
```

**Comment by empierre** [comment]
Hello,

  have you some logs before ? 

  do you use some PlanID for your rooms ? 

  what is the content of  the page http://192.168.X.XXX:XXXX?type=devices&amp;filter=utility&amp;order=Name

**Comment by empierre** [comment]
I launched a build for Docker I hope correcting this.

looks like you have no utility devices right ?

**Comment by CondormanFr** [comment]
Exactly, I use RoomID and probably no utility. (the url show me the domoticz desktop ..)

**Comment by empierre** [comment]
ok new build in docker finished, you can test

**Comment by empierre** [comment]
https://github.com/indexzero/nconf/issues/219

**Comment by empierre** [comment]
is that now ok for you ?

**Comment by CondormanFr** [comment]
No, still get error with latests release :  

```
info: Domoticz server: http://192.168.1.XXX:XXXX
stdout
10:29:40
info: Node version: 4.4.3
stdout
10:29:40
info: MDAH version: MyDomoAtHomeRG 0.1.34
stdout
10:29:40
info: OS version: Linux linux 3.10.35
stdout
10:29:40
info: Hostname: mdah 172.17.0.3 in /root
stdout
10:29:40
info: MDAH port: 3002
stdout
10:29:41
info: Refreshing version cache: v0.1.34
stdout
10:29:44
info:  url=http://192.168.1.XXX:XXXX?type=devices&amp;filter=utility&amp;order=Name, User-Agent=request
stdout
10:29:44
undefined:1
stdout
10:29:44
&lt;!DOCTYPE html&gt;
stdout
10:29:44
^
stdout
10:29:44
stdout
10:29:44
SyntaxError: Unexpected token &lt;
stdout
10:29:44
    at Object.parse (native)
stdout
10:29:44
    at Request._callback (/usr/share/mydomoathome/app/mdah.js:2215:18)
stdout
10:29:44
    at Request.self.callback (/usr/share/mydomoathome/app/node_modules/request/request.js:200:22)
stdout
10:29:44
    at emitTwo (events.js:87:13)
stdout
10:29:44
    at Request.emit (events.js:172:7)
stdout
10:29:44
    at Request.&lt;anonymous&gt; (/usr/share/mydomoathome/app/node_modules/request/request.js:1067:10)
stdout
10:29:44
    at emitOne (events.js:82:20)
stdout
10:29:44
    at Request.emit (events.js:169:7)
stdout
10:29:44
    at IncomingMessage.&lt;anonymous&gt; (/usr/share/mydomoathome/app/node_modules/request/request.js:988:12)
stdout
10:29:44
    at emitNone (events.js:72:20)
stdout
10:29:44
error: Forever detected script exited with code: 1
stdout
10:29:44
error: Script restart attempt #2
```

**Comment by empierre** [comment]
if new build nothung to do,  on old add /json. htm to the env server string

**Comment by CondormanFr** [comment]
New build failed on docker. 
I used the old one with adding /json.htm to my DOMO env var and it works again. Thanks.
