### ISSUE TITLE
SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by CondormanFr** [empierre/MyDomoAtHome#123]
Bonjour,

Depuis quelques jours, MyDomoAtHome ne démarre plus sur mon synology.
Je suis en version 0.1.52

```
info:  url=http://192.168.1.110:8084/json.htm?type=devices&filter=utility&order=Name, User-Agent=request
info: Domoticz server - energy devices: {"82188":"520.0","0001104":"0.5","0001101":"0.0","0000011":"0.5"}
::ffff:192.168.1.241 - - [04/Jul/2016:00:59:55 +0000] "GET /devices HTTP/1.1" 200 9339 "-" "-"
info:  url=http://192.168.1.110:8084/json.htm?type=devices&filter=utility&order=Name, User-Agent=request
info: Domoticz server - energy devices: {"82188":"510.0","0001104":"0.5","0001101":"0.0","0000011":"0.5"}
undefined:2208
         "PlanIDs" : [ 2 ]


SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Request._callback (/volume1/@appstore/MyDomoAtHome/app/mdah.js:2242:29)
    at Request.self.callback (/volume1/@appstore/MyDomoAtHome/app/node_modules/request/request.js:200:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/volume1/@appstore/MyDomoAtHome/app/node_modules/request/request.js:1067:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/volume1/@appstore/MyDomoAtHome/app/node_modules/request/request.js:988:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)

```

**Comment by empierre** [comment]
hello,

  peut-tu m'envoyer le contenu de:
http://192.168.1.110:8084/json.htm?type=devices&filter=utility&order=Name

**Comment by empierre** [comment]
bon je n'arrive pas à reproduire, et le json que tu m'as donné est bien formatté... je sèche... et un reboot du syno si cela n'a pas été fait depuis longtemps ?

**Comment by CondormanFr** [comment]
Effectivement, avec un reboot (+ l'update 2 de DSM) , c'est rentré dans l'ordre. Etrange ...

**Comment by CondormanFr** [comment]
Je me suis réjouis un peu vite, cela a fonctionné hier soir et ce matin, j'ai de nouveau  l'erreur 'unexpected end of input'...

**Comment by empierre** [comment]
et tu es sur la dernière image docker ?

**Comment by CondormanFr** [comment]
Non, sur le package synology

**Comment by empierre** [comment]
toujours des problèles ?
