### ISSUE TITLE
Application stops after Error: read ECONNRESET

### ISSUE THREAD

**Issue by mcwieger** [empierre/MyDomoAtHome#152]
I have MyDomoAtHome installed on a Synology DS414 (0.2.26). Since the latest updates (past weeks), the application stops unexpectedly after a number of hours. During operation, application functions as expected. The log file shows the following:

```
warn: basic configuration not found in /etc/mydomoathome/config.json, defaulting
warn: domoticz access configuration not found in /etc/mydomoathome/config.json, defaulting
info: Domoticz server: http://127.0.0.1:8084/json.htm
info: Node version: 4.8.4
info: MDAH version: MyDomoAtHome 0.2.26
info: OS version: Linux linux 3.2.40
info: Hostname: NAS 192.168.2.201 in /root /usr/local/mydomoathome
info: MDAH port: 3002
info: Refreshing version cache: v0.2.26
/volume1/@appstore/MyDomoAtHome/app/node_modules/sync-request/index.js:37
    throw new Error(response.error.message || response.error || response);
    ^

Error: read ECONNRESET
    at doRequest (/volume1/@appstore/MyDomoAtHome/app/node_modules/sync-request/index.js:37:11)
    at DevCamera (/volume1/@appstore/MyDomoAtHome/app/mdah.js:1624:15)
    at Request._callback (/volume1/@appstore/MyDomoAtHome/app/mdah.js:2656:22)
    at Request.self.callback (/volume1/@appstore/MyDomoAtHome/app/node_modules/request/request.js:200:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/volume1/@appstore/MyDomoAtHome/app/node_modules/request/request.js:1067:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/volume1/@appstore/MyDomoAtHome/app/node_modules/request/request.js:988:12)
```

Any ideas about the issue?

**Comment by empierre** [comment]
read ECONNRESET

this is a low level socket message, not application

**Comment by mcwieger** [comment]
What does that mean? And how can I resolve that?

**Comment by empierre** [comment]
it means your client has dropped the connection, I see the IP is localhost,
maybe this is a domoticz access rights, check your locka network
configuration within domoticz
