### ISSUE TITLE
ReferenceError: tempmode is not defined

### ISSUE THREAD

**Issue by the1chief** [empierre/MyDomoAtHome#157]
Tempmode is not defined.

info: Domoticz server: http://127.0.0.1:8084/json.htm
info: Node version: 4.8.4
info: MDAH version: MyDomoAtHome 0.2.32
info: OS version: Linux linux 3.2.40
info: Hostname: NAS 192.168.1.14 in /root /root
info: Refreshing version cache: v0.2.32
/volume2/@appstore/MyDomoAtHome/app/mdah.js:1326
            params.push({"key": "Value", "value": data.Temp, "unit": "°"+tempmode,"graphable": "true"});
                                                                         ^

ReferenceError: tempmode is not defined
    at DevTH (/volume2/@appstore/MyDomoAtHome/app/mdah.js:1326:74)
    at Request._callback (/volume2/@appstore/MyDomoAtHome/app/mdah.js:2544:37)
    at Request.self.callback (/volume2/@appstore/MyDomoAtHome/app/node_modules/request/request.js:200:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.

**Comment by empierre** [comment]
you need to create a /etc/mydomoathome/config.json see https://github.com/empierre/MyDomoAtHome

**Comment by the1chief** [comment]
Thank you
