### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:8084

### ISSUE THREAD

**Issue by mcwieger** [empierre/MyDomoAtHome#165]
After updating to DSM 6.1.6-15266 on Synology I get the following error:

info: Domoticz server: http://127.0.0.1:8084/json.htm
info: Node version: 4.8.7
info: MDAH version: MyDomoAtHome 0.2.36
info: OS version: Linux linux 3.2.40
info: Hostname: NAS 192.168.2.201 in /root /root
info: Refreshing version cache: v0.2.36
/volume1/@appstore/MyDomoAtHome/app/node_modules/sync-request/index.js:37
    throw new Error(response.error.message || response.error || response);
    ^

Error: connect ECONNREFUSED 127.0.0.1:8084
    at doRequest (/volume1/@appstore/MyDomoAtHome/app/node_modules/sync-request/index.js:37:11)
    at DevCamera (/volume1/@appstore/MyDomoAtHome/app/mdah.js:1630:15)
    at Request._callback (/volume1/@appstore/MyDomoAtHome/app/mdah.js:2669:22)
    at Request.self.callback (/volume1/@appstore/MyDomoAtHome/app/node_modules/request/request.js:200:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/volume1/@appstore/MyDomoAtHome/app/node_modules/request/request.js:1067:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/volume1/@appstore/MyDomoAtHome/app/node_modules/request/request.js:988:12)

Could you check what's going on?

**Comment by empierre** [comment]
Hello,

  Looks domoticz on 8084 is not responding ?
