### ISSUE TITLE
 Objects no longer visible in Imperihome with MDAH

### ISSUE THREAD

**Issue by Kouwe-sudo** [empierre/MyDomoAtHome#187]
I installed Node-red on my Pi 3b. This came with an upgrade of node.js to version V12.14.1 and of NPM version 6.13.4

Since then I can’t get my objects visible in Imperihome. When I redo the configuration on my Imperihome I get ‘success' and it shows that 150 object are discovered but as soon as I reload the objects in the app (running on an android tablet) they are disappeared.

The log says this:

```
Jan 18 09:45:07 raspberrypi MDAH[456]: (node:31038) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
Jan 18 09:45:07 raspberrypi MDAH[456]: /usr/share/mydomoathome/app/mdah.js:918
Jan 18 09:45:07 raspberrypi MDAH[456]:     var res = data.Data.match(ptrn).slice(1);
Jan 18 09:45:07 raspberrypi MDAH[456]:                                    ^
Jan 18 09:45:07 raspberrypi MDAH[456]: TypeError: Cannot read property 'slice' of null
Jan 18 09:45:07 raspberrypi MDAH[456]:     at DevGenericSensorT (/usr/share/mydomoathome/app/mdah.js:918:36)
Jan 18 09:45:07 raspberrypi MDAH[456]:     at Request._callback (/usr/share/mydomoathome/app/mdah.js:2612:45)
Jan 18 09:45:07 raspberrypi MDAH[456]:     at Request.self.callback (/usr/share/mydomoathome/app/node_modules/request/request.js:200:22)
Jan 18 09:45:07 raspberrypi MDAH[456]:     at Request.emit (events.js:223:5)
Jan 18 09:45:07 raspberrypi MDAH[456]:     at Request.<anonymous> (/usr/share/mydomoathome/app/node_modules/request/request.js:1067:10)
Jan 18 09:45:07 raspberrypi MDAH[456]:     at Request.emit (events.js:228:7)
Jan 18 09:45:07 raspberrypi MDAH[456]:     at IncomingMessage.<anonymous> (/usr/share/mydomoathome/app/node_modules/request/request.js:988:12)
Jan 18 09:45:07 raspberrypi MDAH[456]:     at IncomingMessage.emit (events.js:228:7)
Jan 18 09:45:07 raspberrypi MDAH[456]:     at endReadableNT (_stream_readable.js:1185:12)
Jan 18 09:45:07 raspberrypi MDAH[456]:     at processTicksAndRejections (internal/process/task_queues.js:81:21)
Jan 18 09:45:07 raspberrypi MDAH[456]: error: Forever detected script exited with code: 1
Jan 18 09:45:07 raspberrypi MDAH[456]: error: Script restart attempt #3
Jan 18 09:45:09 raspberrypi MDAH[456]: info: Domoticz server: http://192.168.0.130:8080/json.htm
Jan 18 09:45:09 raspberrypi MDAH[456]: info: Node version: 12.14.1
Jan 18 09:45:09 raspberrypi MDAH[456]: info: MDAH version: MyDomoAtHome 0.2.39
Jan 18 09:45:09 raspberrypi MDAH[456]: info: OS version: Linux linux 4.19.93-v7+
Jan 18 09:45:09 raspberrypi MDAH[456]: info: Hostname: raspberrypi 10.8.0.1 in /var/www /
Jan 18 09:45:09 raspberrypi MDAH[456]: info: Refreshing version cache: v0.2.39

```

It seems it has something to do with ‘Forever’ which is no longer supported. I’m unable to reinstall it without destroying my Node-red. Are you familiar with this problem? And even more important do you have time to look into this problem and fix it? I’m sure more people will run into this problem when time goes by.

**Comment by empierre** [comment]
Hello,

  Nothing with forever that is just a daemon to restart if failure.

  Can you send to domoticz@e-nef.com the result of:
http://192.168.0.130:8080/json.htm
